
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlkznudjiicipdwrkpxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsa3pudWRqaWljaXBkd3JrcHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTQ4NDMsImV4cCI6MjA2MDA3MDg0M30.TnVZpNybskkhS8nu9XnzpcI1Uu5VocYJ4GMHgRSPSFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
